### ISSUE TITLE
 Can not inflate file .bin.gz file too large

### ISSUE THREAD

**Issue by phanminhtien** [laukik-hase/esp_compression#2]
When I try to compress file firmware.bin about 650KB into firmware.bin.gz file, it succeeds. But when I inflate firmware.bin.gz file as in the example spiffs_zlib, it doesn't work. Error message : File I/O Error. 
If possible, please try compressing and decompressing a large file in the example spiffs_zlib. Thank you very much.

**Comment by phanminhtien** [comment]
/

**Comment by nopnop2002** [comment]
@phanminhtien 

Try this:
https://github.com/nopnop2002/esp-idf-brotli

**Comment by phanminhtien** [comment]
@nopnop2002 thank you for your help.
